# Generated by Django 6.1 on 2026-08-21 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0003_doctortimeoff'),
        ('patients', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctorprofile')),
                ('doctor_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.doctorservice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-appointment_date', '-appointment_time'],
                'indexes': [models.Index(fields=['doctor', 'appointment_date', 'appointment_time'], name='appointment_doctor_slot_idx'), models.Index(fields=['patient', 'appointment_date', 'appointment_time'], name='appointment_patient_slot_idx'), models.Index(fields=['status', 'appointment_date'], name='appointment_status_date_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED'])), fields=('doctor', 'appointment_date', 'appointment_time'), name='unique_active_doctor_slot'), models.CheckConstraint(condition=models.Q(('appointment_date__isnull', False)), name='appointment_date_required')],
            },
        ),
    ]
