# Generated by Django 6.1 on 2026-08-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_delete_doctorprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientProfile',
        ),
    ]
