@baseUrl = http://127.0.0.1:8000/api/auth
### Register
POST {{baseUrl}}/register/
Content-Type: application/json

{
    "email": "patient2@example.com",
    "first_name": "Mona",
    "last_name": "Ali",
    "password": "StrongPassword123!",
    "password_confirm": "StrongPassword123!"
}


### Login
POST {{baseUrl}}/login/
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123"
}

###
POST {{baseUrl}}/login/
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123"
}
###
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NTc5MDkzLCJpYXQiOjE3ODc0OTI2OTMsImp0aSI6IjFiYjZhNTlmNzMzZjRhODBiMjg5MGIwZjYxNzAwZWE4IiwidXNlcl9pZCI6IjIifQ.kh_j0B95zaTcqn1xxHalf9z264h6W4R57PmOZMKTnTc
### Get Me
GET {{baseUrl}}/me/
Authorization: Bearer {{accessToken}}

@refreshToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4ODA5NzYxMSwiaWF0IjoxNzg3NDkyODExLCJqdGkiOiJmM2RiMWY5MmU4NWY0ODBkOGMwNzZiMDQ4MWU3NTIxNSIsInVzZXJfaWQiOiIyIn0.nd2Cw4Lo2gmHbpkVOM3B2f-kVmXdHlPQFtEYj-pqnlI

### Refresh Token
POST {{baseUrl}}/token/refresh/
Content-Type: application/json

{
    "refresh": "{{refreshToken}}"
}

### Change Password
POST {{baseUrl}}/change-password/
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "old_password": "StrongPassword123!",
    "new_password": "NewStrongPassword123!",
    "new_password_confirm": "NewStrongPassword123!"
}

### Forgot Password
POST {{baseUrl}}/forgot-password/
Content-Type: application/json

{
    "email": "patient1@example.com"
}


### Reset Password
POST {{baseUrl}}/reset-password/
Content-Type: application/json

{
    "uid": "Mg",
    "token": "ddryrn-678a15996db75f54ba8e600896e12c05",
    "new_password": "NewStrongPassword1234!",
    "new_password_confirm": "NewStrongPassword1234!"
}

### Get all patients - Admin
GET http://127.0.0.1:8000/api/patients/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NjQ4MDMyLCJpYXQiOjE3ODc1NjE2MzIsImp0aSI6IjUyMWVkZTYxYzc1MTRjNDNhYWJkYmRhYTkyMzdlMTRhIiwidXNlcl9pZCI6IjEifQ.H-Blst8t3jGV9GGu6_vIOUz-mQfPZk2LitJTmqbil6I

### Get all patients - Patient
GET http://127.0.0.1:8000/api/patients/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NjQ4MjAxLCJpYXQiOjE3ODc1NjE4MDEsImp0aSI6ImE1OWU0YWEwNjljYjQ1ODU5NmZhNjdmYzc5Y2Q4ZWVhIiwidXNlcl9pZCI6IjIifQ.I2b9yOODWWEPwR3-rTPVNku0prZWPp7aP3aWI3M2XKo

### Get my patient profile
GET http://127.0.0.1:8000/api/patients/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NjQ4MjAxLCJpYXQiOjE3ODc1NjE4MDEsImp0aSI6ImE1OWU0YWEwNjljYjQ1ODU5NmZhNjdmYzc5Y2Q4ZWVhIiwidXNlcl9pZCI6IjIifQ.I2b9yOODWWEPwR3-rTPVNku0prZWPp7aP3aWI3M2XKo

### Update my patient profile
PATCH http://127.0.0.1:8000/api/patients/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NjQ4MjAxLCJpYXQiOjE3ODc1NjE4MDEsImp0aSI6ImE1OWU0YWEwNjljYjQ1ODU5NmZhNjdmYzc5Y2Q4ZWVhIiwidXNlcl9pZCI6IjIifQ.I2b9yOODWWEPwR3-rTPVNku0prZWPp7aP3aWI3M2XKo
Content-Type: application/json

{
    "address": "Sanaa",
    "blood_type": "O+",
    "emergency_contact_name": "Ahmed Ali",
    "emergency_contact_phone": "777777777"
}

### =====================================================
### DOCTORS
### =====================================================

###
POST {{baseUrl}}/login/
Content-Type: application/json

{
    "email": "doctor1@example.com",
    "password": "StrongPassword123!"
}
### 1. Get all doctors - Public
GET http://127.0.0.1:8000/api/doctors/

###
### 2. Get doctor
GET http://127.0.0.1:8000/api/doctors/1/

### 3. Create doctor - Admin
POST http://127.0.0.1:8000/api/doctors/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg4MDEzOTQ1LCJpYXQiOjE3ODc5Mjc1NDUsImp0aSI6ImQ3YmZjZTRhNjNhZDQwNGQ5NTkwN2Y0YmYzOTRjY2QwIiwidXNlcl9pZCI6IjEifQ.OgpHdAuYFzIACBH4EJSLQ1gtUybfI2EQbs5-27w3emY
Content-Type: application/json

{
    "email": "doctor10@example.com",
    "first_name": "Mohammed",
    "last_name": "Ahmed",
    "phone": "777123456",
    "password": "StrongPassword123!",
    "specialization": "Cardiology",
    "license_number": "DOC-0010",
    "bio": "Cardiology specialist",
    "consultation_fee": "50.00"
}

### 4. Create doctor - Normal user
POST http://127.0.0.1:8000/api/doctors/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NjQ4NzkzLCJpYXQiOjE3ODc1NjIzOTMsImp0aSI6ImFiNGZiYzdiNzkxZjQ1ZDA5MjIyMjEwNzc2ZjgxYTBjIiwidXNlcl9pZCI6IjQifQ.eI43gcP-1wczHxGSrUBxGD42GIkn4EKVoPZnq0COFkM
Content-Type: application/json

{
    "email": "doctor3@example.com",
    "first_name": "Ali",
    "last_name": "Hassan",
    "password": "StrongPassword123!",
    "specialization": "Dentist",
    "license_number": "DOC-003",
    "consultation_fee": "30.00"
}
###
### Test Django Routing

GET http://127.0.0.1:8000/api/dashboard-test/

### 6. Duplicate license number
GET http://127.0.0.1:8000/api/doctors/dashboard/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg4MTcwNTA2LCJpYXQiOjE3ODgwODQxMDYsImp0aSI6IjIxOGI0ZWZkMDc0OTRkZDBhODliODA1NThjZjVmZmJiIiwidXNlcl9pZCI6IjQifQ.hy8TNE3UEnvSBRqniQkmG0ceNheqx4yRL5-3RZDUsio

### 6. Duplicate license numbereyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg4MTY5NDI3LCJpYXQiOjE3ODgwODMwMjcsImp0aSI6IjZiNzcxOWRiN2E1YjQzZjU4ZDk1ZTBhMTI5MmJlYWM1IiwidXNlcl9pZCI6IjQifQ.unBTAC_z5IJRMlUBqLgxLWeOKSzc89LKJ9lVDtAHOLA
POST http://127.0.0.1:8000/api/doctors/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NjQ4NTkwLCJpYXQiOjE3ODc1NjIxOTAsImp0aSI6ImViNTI3MGMxNTE4NDQ0YTM5YzY2ODU1Y2MwNDAzZmNhIiwidXNlcl9pZCI6IjEifQ.qkjs9HX2vUDqxz42tk2fkguUoSQLk3wQZ5-7zxGLHQM
Content-Type: application/json

{
    "email": "doctor3@example.com",
    "first_name": "Test",
    "last_name": "Doctor",
    "password": "StrongPassword123!",
    "specialization": "Neurology",
    "license_number": "DOC-003",
    "consultation_fee": "60.00"
}

### =====================================================
### DOCTOR SCHEDULE
### =====================================================

### 8. Create schedule
POST http://127.0.0.1:8000/api/doctor-schedules/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg4MTcwOTIxLCJpYXQiOjE3ODgwODQ1MjEsImp0aSI6IjEzMjUyZDdmYmJlMjQ1YjhhYjA1ODVkZGNjMzBmODlhIiwidXNlcl9pZCI6IjQifQ.fSDZkBtyTsVTAX9mWgoi64kuQgvp-tiqOH-KebdbrtA
Content-Type: application/json

{
    "day_of_week": 6,
    "start_time": "09:00:00",
    "end_time": "13:00:00",
    "is_active": true
}

### =====================================================
### DOCTOR TIME OFF
### =====================================================

### 12. Create time off
POST http://127.0.0.1:8000/api/doctor-time-offs/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NjQ4OTk0LCJpYXQiOjE3ODc1NjI1OTQsImp0aSI6ImEyMDcxOWU0YzYwMjRjYmQ5ODQwM2FiMzJjZDYxZWMyIiwidXNlcl9pZCI6IjQifQ.cuNOCpiDht1XpvmoR2dTZ2cx6mHRKS94t8ftjd3rJHA
Content-Type: application/json

{
    "start_date": "2026-09-01",
    "end_date": "2026-09-05",
    "reason": "Annual vacation",
    "is_active": true
}

### =====================================================
### SERVICES
### =====================================================

### 1. Get all services
GET http://127.0.0.1:8000/api/services/

### 2. Get active services
GET http://127.0.0.1:8000/api/services/?is_active=True

### 5. Create service - Admin
POST http://127.0.0.1:8000/api/services/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg4MDExNTU2LCJpYXQiOjE3ODc5MjUxNTYsImp0aSI6ImM0NjNmZTcwMjQwNzQ3NjlhMmEzMzY1MzRlNmZjMDNkIiwidXNlcl9pZCI6IjEifQ.BzX19w8eIJavHAEUC-fvWGU5Iy67a0fEIfaZDkqtH68
Content-Type: application/json

{
    "name": "Cardiology",
    "description": "Specialized cardiology consultation",
    "is_active": true
}

### =====================================================
### DOCTOR SERVICES
### =====================================================

### 7. Create doctor service - Superuser
POST http://127.0.0.1:8000/api/doctor-services/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NjQ4NTkwLCJpYXQiOjE3ODc1NjIxOTAsImp0aSI6ImViNTI3MGMxNTE4NDQ0YTM5YzY2ODU1Y2MwNDAzZmNhIiwidXNlcl9pZCI6IjEifQ.qkjs9HX2vUDqxz42tk2fkguUoSQLk3wQZ5-7zxGLHQM
Content-Type: application/json

{
    "doctor": 1,
    "service": 1,
    "price": "50.00",
    "duration": 30,
    "is_active": true
}

### 10. Get doctor services
GET http://127.0.0.1:8000/api/doctor-services/

### 4. Get service details
GET http://127.0.0.1:8000/api/services/1/


### =====================================================
### APPOINTMENTS
### =====================================================

### Login
POST {{baseUrl}}/login/
Content-Type: application/json

{
    "email": "patient1@example.com",
    "password": "NewStrongPassword1234!"
}
### 1. Create appointment
POST http://127.0.0.1:8000/api/appointments/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NjQ5OTU0LCJpYXQiOjE3ODc1NjM1NTQsImp0aSI6IjA0ZDAzN2MwMGM3YTQ4YjFhYWE5Y2Q1YTRkMzczODI4IiwidXNlcl9pZCI6IjIifQ.t71pX9Co8A98i4gRo_KSlNSgKmv_JCKueSGOODqxXOo
Content-Type: application/json

{
    "doctor_service": 1,
    "appointment_date": "2026-08-31",
    "appointment_time": "09:00:00",
    "notes": "I have chest pain."
}

### 8. My appointments
GET http://127.0.0.1:8000/api/appointments/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg4MTczOTMwLCJpYXQiOjE3ODgwODc1MzAsImp0aSI6IjlkNTJjOGE0N2UyZjQ5NDVhZGFlNmViZmE3NWExZDFkIiwidXNlcl9pZCI6IjQifQ.BAOasctti0VMiLsko38OhIRAdI1P9FgqU137r2Pme3I


### =====================================================
### CONFIRM
### =====================================================

### 10. Confirm appointment
POST http://127.0.0.1:8000/api/appointments/4/confirm/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg4MTcyNzg0LCJpYXQiOjE3ODgwODYzODQsImp0aSI6ImRiNDIxZDQwYzQ4ODRiMWNhYzliY2U0ZWU3MmI0MDhmIiwidXNlcl9pZCI6IjQifQ.XOfxEqYZdMCK7cg4JYGmNPRjcnt0B3W1s_P3q6k9jy8
Content-Type: application/json

### Start Consultation
POST http://127.0.0.1:8000/api/consultations/start/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NjUwNjY0LCJpYXQiOjE3ODc1NjQyNjQsImp0aSI6IjVlMzRlNDEzN2E4OTRmYTU5ZWZkYWM1NDIwYjdjYzljIiwidXNlcl9pZCI6IjQifQ.M6KfMwfRQsZe7h_j2zMda4Oid8AT8U-Fum-JL-RG8CE
Content-Type: application/json

{
    "appointment": 1
}

### List consultations
GET http://127.0.0.1:8000/api/consultations/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NjUwNjY0LCJpYXQiOjE3ODc1NjQyNjQsImp0aSI6IjVlMzRlNDEzN2E4OTRmYTU5ZWZkYWM1NDIwYjdjYzljIiwidXNlcl9pZCI6IjQifQ.M6KfMwfRQsZe7h_j2zMda4Oid8AT8U-Fum-JL-RG8CE
###
POST http://127.0.0.1:8000/api/consultations/1/diagnoses/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NjUwNjY0LCJpYXQiOjE3ODc1NjQyNjQsImp0aSI6IjVlMzRlNDEzN2E4OTRmYTU5ZWZkYWM1NDIwYjdjYzljIiwidXNlcl9pZCI6IjQifQ.M6KfMwfRQsZe7h_j2zMda4Oid8AT8U-Fum-JL-RG8CE
Content-Type: application/json

{
    "name": "Common Cold",
    "description": "Viral upper respiratory infection."
}
###
POST http://127.0.0.1:8000/api/consultations/1/notes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NjUwNjY0LCJpYXQiOjE3ODc1NjQyNjQsImp0aSI6IjVlMzRlNDEzN2E4OTRmYTU5ZWZkYWM1NDIwYjdjYzljIiwidXNlcl9pZCI6IjQifQ.M6KfMwfRQsZe7h_j2zMda4Oid8AT8U-Fum-JL-RG8CE
Content-Type: application/json

{
    "chief_complaint": "Headache and fever",
    "symptoms": "Fever, headache, fatigue",
    "clinical_notes": "Patient appears stable."
}

###
POST http://127.0.0.1:8000/api/consultations/1/prescription/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NjUwNjY0LCJpYXQiOjE3ODc1NjQyNjQsImp0aSI6IjVlMzRlNDEzN2E4OTRmYTU5ZWZkYWM1NDIwYjdjYzljIiwidXNlcl9pZCI6IjQifQ.M6KfMwfRQsZe7h_j2zMda4Oid8AT8U-Fum-JL-RG8CE
Content-Type: application/json

{
    "notes": "Take medication after meals."
}

###
POST http://127.0.0.1:8000/api/prescription-items/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NjUwNjY0LCJpYXQiOjE3ODc1NjQyNjQsImp0aSI6IjVlMzRlNDEzN2E4OTRmYTU5ZWZkYWM1NDIwYjdjYzljIiwidXNlcl9pZCI6IjQifQ.M6KfMwfRQsZe7h_j2zMda4Oid8AT8U-Fum-JL-RG8CE
Content-Type: application/json

{
    "prescription": 1,
    "medicine_name": "Paracetamol2",
    "dosage": "500 mg",
    "frequency": "3 times daily",
    "duration": "5 days",
    "instructions": "Take after meals."
}

###
GET http://127.0.0.1:8000/api/consultations/1/prescription/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NjUwNjY0LCJpYXQiOjE3ODc1NjQyNjQsImp0aSI6IjVlMzRlNDEzN2E4OTRmYTU5ZWZkYWM1NDIwYjdjYzljIiwidXNlcl9pZCI6IjQifQ.M6KfMwfRQsZe7h_j2zMda4Oid8AT8U-Fum-JL-RG8CE
Content-Type: application/json

###
GET http://127.0.0.1:8000/api/payments/invoices/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NjUxNTY3LCJpYXQiOjE3ODc1NjUxNjcsImp0aSI6ImE2ZjRhMTgxMWIzMDRlZjM4NTgwMTJjZGM4ODdjNTMwIiwidXNlcl9pZCI6IjIifQ.r8k8O5eAQwxewRMX4QxXveFx3VoCJWsDYLHUZTWVk8w
Content-Type: application/json

###
GET http://127.0.0.1:8000/api/payments/invoices/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NjUxNTY3LCJpYXQiOjE3ODc1NjUxNjcsImp0aSI6ImE2ZjRhMTgxMWIzMDRlZjM4NTgwMTJjZGM4ODdjNTMwIiwidXNlcl9pZCI6IjIifQ.r8k8O5eAQwxewRMX4QxXveFx3VoCJWsDYLHUZTWVk8w
Content-Type: application/json

###
POST http://127.0.0.1:8000/api/payments/payments/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NjUxNTY3LCJpYXQiOjE3ODc1NjUxNjcsImp0aSI6ImE2ZjRhMTgxMWIzMDRlZjM4NTgwMTJjZGM4ODdjNTMwIiwidXNlcl9pZCI6IjIifQ.r8k8O5eAQwxewRMX4QxXveFx3VoCJWsDYLHUZTWVk8w
Content-Type: application/json

{
    "invoice": 1,
    "amount": "50.00",
    "method": "CASH",
    "transaction_reference": "TXN-001"
}

###
POST http://127.0.0.1:8000/api/payments/payments/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NjUxNTY3LCJpYXQiOjE3ODc1NjUxNjcsImp0aSI6ImE2ZjRhMTgxMWIzMDRlZjM4NTgwMTJjZGM4ODdjNTMwIiwidXNlcl9pZCI6IjIifQ.r8k8O5eAQwxewRMX4QxXveFx3VoCJWsDYLHUZTWVk8w
Content-Type: application/json

{
    "invoice": 1,
    "amount": "10.00",
    "method": "CASH"
}
