# Generated by Django 6.1 on 2026-08-21 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorTimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_offs', to='doctors.doctorprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['doctor', 'start_date', 'end_date', 'is_active'], name='doctor_timeoff_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='timeoff_end_after_start')],
            },
        ),
    ]
